name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows manual trigger

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, repositories
          plugin_languages: yes
          plugin_followup: yes
          plugin_activity: yes
          plugin_isocalendar: yes
          plugin_skyline: yes
          plugin_skyline_year: 2025
          plugin_skyline_frames: 6
          plugin_skyline_quality: 1
